#!/bin/bash

set -e

export VT_VERSION=1.00
export ANDROID_HOME=~/Android
export ANDROID_NDK_HOST=linux-x86_64
export ANDROID_NDK_PLATFORM=android-23
export ANDROID_NDK_TOOLCHAIN_VERSION=4.9
export ANDROID_API_VERSION=android-23
export ANDROID_NDK_ROOT=$ANDROID_HOME/Sdk/ndk-bundle
export ANDROID_SDK_ROOT=$ANDROID_HOME/Sdk

export JAVA_HOME=/usr/lib/jvm/java-1.8.0-openjdk-amd64
export PATH=$PATH:$ANDROID_HOME/Sdk/tools:/usr/bin:$JAVA_HOME/bin

rm -rf build/android/*

# armv7
export PATH=$HOME/Qt/5.13.2/android_armv7/bin/:$PATH
export ANDROID_NDK_TOOLCHAIN_PREFIX=arm-linux-androideabi
export ANDROID_NDK_TOOLS_PREFIX=arm-linux-androideabi

# Mobile
qmake -config release "CONFIG += release_android build_mobile"
make clean
make -j8
make install INSTALL_ROOT=build/android/build
androiddeployqt --gradle --no-gdbserver --output build/android/build --input android-libcalibike_tool.so-deployment-settings.json --android-platform android-23

mv build/android/build/build/outputs/apk/build-debug.apk build/android/calibike_mobile.apk
mv build/android/calibike_mobile.apk build/android/calibike_mobile_$VT_VERSION.apk
rm -rf build/android/build
rm -f build/android/libcalibike_tool.so
